name: flutter_test_task
description: Task application

version: 1.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  smooth_page_indicator: ^0.2.0
  email_validator: ^1.0.6
  firebase_core: ^0.5.2
  firebase_auth: ^0.18.3
  sqflite: ^1.3.2+1
  shared_preferences: ^0.5.12+4
  path_provider: ^1.6.24
  http: ^0.12.2
  font_awesome_flutter: ^8.10.0
  smooth_star_rating: ^1.1.1
  flutter_launcher_icons: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  fonts:
    - family: MotionPicture
      fonts:
        - asset: fonts/MotionPicture_PersonalUseOnly.ttf
          weight: 900
    - family: Aaargh
      fonts:
        - asset: fonts/Aaargh.ttf
          weight: 900

  uses-material-design: true
  assets:
    - assets/images/